import paramiko, sys
sys.stdout.reconfigure(encoding='utf-8')
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('47.239.193.33', username='admin', password='A123456', timeout=15)
_, o, _ = ssh.exec_command("curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/api/health 2>/dev/null", timeout=10)
print('Health:', o.read().decode().strip())
_, o, _ = ssh.exec_command('ps aux | grep uvicorn | grep -v grep', timeout=10)
print(o.read().decode().strip())
ssh.close()
