export interface AdMarketConfig {
  countryCode: string;
  countryNameZh: string;
  languageCode: string;
  languageName: string;
  style: string;
  currencyCode: string;
  shippingLabel: string;
  returnLabel: string;
  genericPromotionTarget: string;
  snippetHeader: string;
  priceLanguageCode: string;
  promotionLanguageCode: string;
}

const DEFAULT_MARKET: AdMarketConfig = {
  countryCode: "US",
  countryNameZh: "美国",
  languageCode: "en",
  languageName: "English (US)",
  style: "直接、行动导向、强调价值和优惠",
  currencyCode: "USD",
  shippingLabel: "Free US Shipping",
  returnLabel: "Easy Returns",
  genericPromotionTarget: "Special Offers",
  snippetHeader: "Brands",
  priceLanguageCode: "en",
  promotionLanguageCode: "en",
};

export const AD_MARKET_MAP: Record<string, AdMarketConfig> = {
  US: DEFAULT_MARKET,
  UK: {
    countryCode: "UK",
    countryNameZh: "英国",
    languageCode: "en",
    languageName: "English (UK)",
    style: "含蓄、品质导向、使用英式表达",
    currencyCode: "GBP",
    shippingLabel: "Free UK Delivery",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Limited-Time Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  GB: {
    countryCode: "GB",
    countryNameZh: "英国",
    languageCode: "en",
    languageName: "English (UK)",
    style: "含蓄、品质导向、使用英式表达",
    currencyCode: "GBP",
    shippingLabel: "Free UK Delivery",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Limited-Time Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  CA: {
    countryCode: "CA",
    countryNameZh: "加拿大",
    languageCode: "en",
    languageName: "English (CA)",
    style: "强调价值、信任感与可持续感",
    currencyCode: "CAD",
    shippingLabel: "Free CA Shipping",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Special Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  AU: {
    countryCode: "AU",
    countryNameZh: "澳大利亚",
    languageCode: "en",
    languageName: "English (AU)",
    style: "轻快直接、强调易用性与日常场景",
    currencyCode: "AUD",
    shippingLabel: "Free AU Shipping",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Special Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  DE: {
    countryCode: "DE",
    countryNameZh: "德国",
    languageCode: "de",
    languageName: "German",
    style: "严谨、强调品质、参数、效率与可信度",
    currencyCode: "EUR",
    shippingLabel: "Kostenloser Versand",
    returnLabel: "Kostenlose Rückgabe",
    genericPromotionTarget: "Sonderangebote",
    snippetHeader: "Brands",
    priceLanguageCode: "de",
    promotionLanguageCode: "de",
  },
  AT: {
    countryCode: "AT",
    countryNameZh: "奥地利",
    languageCode: "de",
    languageName: "German",
    style: "严谨、强调品质、参数与可信度",
    currencyCode: "EUR",
    shippingLabel: "Kostenloser Versand",
    returnLabel: "Kostenlose Rückgabe",
    genericPromotionTarget: "Sonderangebote",
    snippetHeader: "Brands",
    priceLanguageCode: "de",
    promotionLanguageCode: "de",
  },
  CH: {
    countryCode: "CH",
    countryNameZh: "瑞士",
    languageCode: "de",
    languageName: "German",
    style: "严谨、强调品质、参数与可信度",
    currencyCode: "CHF",
    shippingLabel: "Kostenloser Versand",
    returnLabel: "Kostenlose Rückgabe",
    genericPromotionTarget: "Sonderangebote",
    snippetHeader: "Brands",
    priceLanguageCode: "de",
    promotionLanguageCode: "de",
  },
  FR: {
    countryCode: "FR",
    countryNameZh: "法国",
    languageCode: "fr",
    languageName: "French",
    style: "优雅、重视设计感与品质表达",
    currencyCode: "EUR",
    shippingLabel: "Livraison offerte",
    returnLabel: "Retours faciles",
    genericPromotionTarget: "Offres spéciales",
    snippetHeader: "Brands",
    priceLanguageCode: "fr",
    promotionLanguageCode: "fr",
  },
  // 比利时默认荷兰语（弗拉芒区 ~60% 人口）；如需法语比利时请用 BE-FR
  BE: {
    countryCode: "BE",
    countryNameZh: "比利时（荷兰语）",
    languageCode: "nl",
    languageName: "Dutch (BE)",
    style: "简洁务实、强调清晰价值与可靠性",
    currencyCode: "EUR",
    shippingLabel: "Gratis verzending",
    returnLabel: "Eenvoudig retourneren",
    genericPromotionTarget: "Speciale aanbiedingen",
    snippetHeader: "Brands",
    priceLanguageCode: "nl",
    promotionLanguageCode: "nl",
  },
  // 法语比利时（瓦隆区 + 布鲁塞尔）
  "BE-FR": {
    countryCode: "BE-FR",
    countryNameZh: "比利时（法语）",
    languageCode: "fr",
    languageName: "French (BE)",
    style: "优雅、重视设计感与品质表达",
    currencyCode: "EUR",
    shippingLabel: "Livraison offerte",
    returnLabel: "Retours faciles",
    genericPromotionTarget: "Offres spéciales",
    snippetHeader: "Brands",
    priceLanguageCode: "fr",
    promotionLanguageCode: "fr",
  },
  ES: {
    countryCode: "ES",
    countryNameZh: "西班牙",
    languageCode: "es",
    languageName: "Spanish",
    style: "热情直接、强调优惠和购买动机",
    currencyCode: "EUR",
    shippingLabel: "Envío gratis",
    returnLabel: "Devoluciones fáciles",
    genericPromotionTarget: "Ofertas especiales",
    snippetHeader: "Brands",
    priceLanguageCode: "es",
    promotionLanguageCode: "es",
  },
  IT: {
    countryCode: "IT",
    countryNameZh: "意大利",
    languageCode: "it",
    languageName: "Italian",
    style: "强调品质、风格与价值感",
    currencyCode: "EUR",
    shippingLabel: "Spedizione gratuita",
    returnLabel: "Resi facili",
    genericPromotionTarget: "Offerte speciali",
    snippetHeader: "Brands",
    priceLanguageCode: "it",
    promotionLanguageCode: "it",
  },
  PT: {
    countryCode: "PT",
    countryNameZh: "葡萄牙",
    languageCode: "pt",
    languageName: "Portuguese",
    style: "强调优惠与可信感",
    currencyCode: "EUR",
    shippingLabel: "Envio grátis",
    returnLabel: "Devoluções fáceis",
    genericPromotionTarget: "Ofertas especiais",
    snippetHeader: "Brands",
    priceLanguageCode: "pt",
    promotionLanguageCode: "pt",
  },
  BR: {
    countryCode: "BR",
    countryNameZh: "巴西",
    languageCode: "pt",
    languageName: "Portuguese (BR)",
    style: "热情、强调优惠、社交证明和购买欲",
    currencyCode: "BRL",
    shippingLabel: "Frete grátis",
    returnLabel: "Troca fácil",
    genericPromotionTarget: "Ofertas especiais",
    snippetHeader: "Brands",
    priceLanguageCode: "pt",
    promotionLanguageCode: "pt",
  },
  NL: {
    countryCode: "NL",
    countryNameZh: "荷兰",
    languageCode: "nl",
    languageName: "Dutch",
    style: "简洁务实、强调清晰价值",
    currencyCode: "EUR",
    shippingLabel: "Gratis verzending",
    returnLabel: "Eenvoudig retourneren",
    genericPromotionTarget: "Speciale deals",
    snippetHeader: "Brands",
    priceLanguageCode: "nl",
    promotionLanguageCode: "nl",
  },
  JP: {
    countryCode: "JP",
    countryNameZh: "日本",
    languageCode: "ja",
    languageName: "Japanese",
    style: "礼貌克制、强调品质、服务与信赖",
    currencyCode: "JPY",
    shippingLabel: "全国送料無料",
    returnLabel: "返品対応",
    genericPromotionTarget: "おすすめキャンペーン",
    snippetHeader: "Brands",
    priceLanguageCode: "ja",
    promotionLanguageCode: "ja",
  },
  DK: {
    countryCode: "DK",
    countryNameZh: "丹麦",
    languageCode: "da",
    languageName: "Danish",
    style: "简洁务实、强调品质与实用性",
    currencyCode: "DKK",
    shippingLabel: "Gratis fragt",
    returnLabel: "Nem returnering",
    genericPromotionTarget: "Specialtilbud",
    snippetHeader: "Brands",
    priceLanguageCode: "da",
    promotionLanguageCode: "da",
  },
  SE: {
    countryCode: "SE",
    countryNameZh: "瑞典",
    languageCode: "sv",
    languageName: "Swedish",
    style: "简洁理性、强调品质与可持续性",
    currencyCode: "SEK",
    shippingLabel: "Fri frakt",
    returnLabel: "Enkla returer",
    genericPromotionTarget: "Specialerbjudanden",
    snippetHeader: "Brands",
    priceLanguageCode: "sv",
    promotionLanguageCode: "sv",
  },
  NO: {
    countryCode: "NO",
    countryNameZh: "挪威",
    languageCode: "no",
    languageName: "Norwegian",
    style: "简洁直接、强调品质与信任",
    currencyCode: "NOK",
    shippingLabel: "Gratis frakt",
    returnLabel: "Enkel retur",
    genericPromotionTarget: "Spesialtilbud",
    snippetHeader: "Brands",
    priceLanguageCode: "no",
    promotionLanguageCode: "no",
  },
  FI: {
    countryCode: "FI",
    countryNameZh: "芬兰",
    languageCode: "fi",
    languageName: "Finnish",
    style: "简洁务实、强调效率与可靠性",
    currencyCode: "EUR",
    shippingLabel: "Ilmainen toimitus",
    returnLabel: "Helpot palautukset",
    genericPromotionTarget: "Erikoistarjoukset",
    snippetHeader: "Brands",
    priceLanguageCode: "fi",
    promotionLanguageCode: "fi",
  },
  PL: {
    countryCode: "PL",
    countryNameZh: "波兰",
    languageCode: "pl",
    languageName: "Polish",
    style: "直接、强调优惠与性价比",
    currencyCode: "PLN",
    shippingLabel: "Darmowa dostawa",
    returnLabel: "Łatwe zwroty",
    genericPromotionTarget: "Oferty specjalne",
    snippetHeader: "Brands",
    priceLanguageCode: "pl",
    promotionLanguageCode: "pl",
  },
  CZ: {
    countryCode: "CZ",
    countryNameZh: "捷克",
    languageCode: "cs",
    languageName: "Czech",
    style: "务实直接、强调品质与价值",
    currencyCode: "CZK",
    shippingLabel: "Doprava zdarma",
    returnLabel: "Snadné vrácení",
    genericPromotionTarget: "Speciální nabídky",
    snippetHeader: "Brands",
    priceLanguageCode: "cs",
    promotionLanguageCode: "cs",
  },
  KR: {
    countryCode: "KR",
    countryNameZh: "韩国",
    languageCode: "ko",
    languageName: "Korean",
    style: "强调潮流、品质与用户口碑",
    currencyCode: "KRW",
    shippingLabel: "무료 배송",
    returnLabel: "간편 반품",
    genericPromotionTarget: "특별 할인",
    snippetHeader: "Brands",
    priceLanguageCode: "ko",
    promotionLanguageCode: "ko",
  },
  TR: {
    countryCode: "TR",
    countryNameZh: "土耳其",
    languageCode: "tr",
    languageName: "Turkish",
    style: "热情直接、强调优惠与快速配送",
    currencyCode: "TRY",
    shippingLabel: "Ücretsiz kargo",
    returnLabel: "Kolay iade",
    genericPromotionTarget: "Özel fırsatlar",
    snippetHeader: "Brands",
    priceLanguageCode: "tr",
    promotionLanguageCode: "tr",
  },
  TH: {
    countryCode: "TH",
    countryNameZh: "泰国",
    languageCode: "th",
    languageName: "Thai",
    style: "亲切友好、强调优惠与便利",
    currencyCode: "THB",
    shippingLabel: "จัดส่งฟรี",
    returnLabel: "คืนสินค้าง่าย",
    genericPromotionTarget: "โปรโมชั่นพิเศษ",
    snippetHeader: "Brands",
    priceLanguageCode: "th",
    promotionLanguageCode: "th",
  },
  VN: {
    countryCode: "VN",
    countryNameZh: "越南",
    languageCode: "vi",
    languageName: "Vietnamese",
    style: "热情直接、强调优惠与性价比",
    currencyCode: "VND",
    shippingLabel: "Miễn phí vận chuyển",
    returnLabel: "Đổi trả dễ dàng",
    genericPromotionTarget: "Ưu đãi đặc biệt",
    snippetHeader: "Brands",
    priceLanguageCode: "vi",
    promotionLanguageCode: "vi",
  },
  ID: {
    countryCode: "ID",
    countryNameZh: "印度尼西亚",
    languageCode: "id",
    languageName: "Indonesian",
    style: "友好直接、强调优惠与便利",
    currencyCode: "IDR",
    shippingLabel: "Gratis ongkir",
    returnLabel: "Pengembalian mudah",
    genericPromotionTarget: "Penawaran spesial",
    snippetHeader: "Brands",
    priceLanguageCode: "id",
    promotionLanguageCode: "id",
  },
  MY: {
    countryCode: "MY",
    countryNameZh: "马来西亚",
    languageCode: "ms",
    languageName: "Malay",
    style: "友好直接、强调优惠与便利",
    currencyCode: "MYR",
    shippingLabel: "Penghantaran percuma",
    returnLabel: "Pemulangan mudah",
    genericPromotionTarget: "Tawaran istimewa",
    snippetHeader: "Brands",
    priceLanguageCode: "ms",
    promotionLanguageCode: "ms",
  },
  SA: {
    countryCode: "SA",
    countryNameZh: "沙特阿拉伯",
    languageCode: "ar",
    languageName: "Arabic",
    style: "正式、强调品质与信任",
    currencyCode: "SAR",
    shippingLabel: "شحن مجاني",
    returnLabel: "إرجاع سهل",
    genericPromotionTarget: "عروض خاصة",
    snippetHeader: "Brands",
    priceLanguageCode: "ar",
    promotionLanguageCode: "ar",
  },
  AE: {
    countryCode: "AE",
    countryNameZh: "阿联酋",
    languageCode: "ar",
    languageName: "Arabic",
    style: "正式、强调品质、奢华与信任",
    currencyCode: "AED",
    shippingLabel: "شحن مجاني",
    returnLabel: "إرجاع سهل",
    genericPromotionTarget: "عروض خاصة",
    snippetHeader: "Brands",
    priceLanguageCode: "ar",
    promotionLanguageCode: "ar",
  },
  GR: {
    countryCode: "GR",
    countryNameZh: "希腊",
    languageCode: "el",
    languageName: "Greek",
    style: "友好直接、强调品质与优惠",
    currencyCode: "EUR",
    shippingLabel: "Δωρεάν αποστολή",
    returnLabel: "Εύκολες επιστροφές",
    genericPromotionTarget: "Ειδικές προσφορές",
    snippetHeader: "Brands",
    priceLanguageCode: "el",
    promotionLanguageCode: "el",
  },
  RO: {
    countryCode: "RO",
    countryNameZh: "罗马尼亚",
    languageCode: "ro",
    languageName: "Romanian",
    style: "直接、强调优惠与性价比",
    currencyCode: "RON",
    shippingLabel: "Livrare gratuită",
    returnLabel: "Retururi ușoare",
    genericPromotionTarget: "Oferte speciale",
    snippetHeader: "Brands",
    priceLanguageCode: "ro",
    promotionLanguageCode: "ro",
  },
  HU: {
    countryCode: "HU",
    countryNameZh: "匈牙利",
    languageCode: "hu",
    languageName: "Hungarian",
    style: "务实直接、强调品质与价值",
    currencyCode: "HUF",
    shippingLabel: "Ingyenes szállítás",
    returnLabel: "Könnyű visszaküldés",
    genericPromotionTarget: "Különleges ajánlatok",
    snippetHeader: "Brands",
    priceLanguageCode: "hu",
    promotionLanguageCode: "hu",
  },
  BG: {
    countryCode: "BG",
    countryNameZh: "保加利亚",
    languageCode: "bg",
    languageName: "Bulgarian",
    style: "直接、强调优惠与可信度",
    currencyCode: "BGN",
    shippingLabel: "Безплатна доставка",
    returnLabel: "Лесно връщане",
    genericPromotionTarget: "Специални оферти",
    snippetHeader: "Brands",
    priceLanguageCode: "bg",
    promotionLanguageCode: "bg",
  },
  IN: {
    countryCode: "IN",
    countryNameZh: "印度",
    languageCode: "hi",
    languageName: "Hindi",
    style: "热情直接、强调优惠与性价比",
    currencyCode: "INR",
    shippingLabel: "मुफ़्त शिपिंग",
    returnLabel: "आसान रिटर्न",
    genericPromotionTarget: "विशेष ऑफ़र",
    snippetHeader: "Brands",
    priceLanguageCode: "hi",
    promotionLanguageCode: "hi",
  },
  IE: {
    countryCode: "IE",
    countryNameZh: "爱尔兰",
    languageCode: "en",
    languageName: "English (IE)",
    style: "友好直接、强调品质与价值",
    currencyCode: "EUR",
    shippingLabel: "Free Shipping",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Special Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  NZ: {
    countryCode: "NZ",
    countryNameZh: "新西兰",
    languageCode: "en",
    languageName: "English (NZ)",
    style: "轻快友好、强调品质与日常场景",
    currencyCode: "NZD",
    shippingLabel: "Free NZ Shipping",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Special Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  SG: {
    countryCode: "SG",
    countryNameZh: "新加坡",
    languageCode: "en",
    languageName: "English (SG)",
    style: "简洁直接、强调品质与便利",
    currencyCode: "SGD",
    shippingLabel: "Free Shipping",
    returnLabel: "Easy Returns",
    genericPromotionTarget: "Special Offers",
    snippetHeader: "Brands",
    priceLanguageCode: "en",
    promotionLanguageCode: "en",
  },
  HK: {
    countryCode: "HK",
    countryNameZh: "中国香港",
    languageCode: "zh_TW",
    languageName: "Traditional Chinese",
    style: "简洁务实、强调品质与优惠",
    currencyCode: "HKD",
    shippingLabel: "免費送貨",
    returnLabel: "輕鬆退貨",
    genericPromotionTarget: "特別優惠",
    snippetHeader: "Brands",
    priceLanguageCode: "zh_TW",
    promotionLanguageCode: "zh_TW",
  },
  TW: {
    countryCode: "TW",
    countryNameZh: "中国台湾",
    languageCode: "zh_TW",
    languageName: "Traditional Chinese",
    style: "亲切实用、强调品质与CP值",
    currencyCode: "TWD",
    shippingLabel: "免運費",
    returnLabel: "輕鬆退貨",
    genericPromotionTarget: "限時優惠",
    snippetHeader: "Brands",
    priceLanguageCode: "zh_TW",
    promotionLanguageCode: "zh_TW",
  },
  RU: {
    countryCode: "RU",
    countryNameZh: "俄罗斯",
    languageCode: "ru",
    languageName: "Russian",
    style: "直接务实、强调品质与优惠",
    currencyCode: "RUB",
    shippingLabel: "Бесплатная доставка",
    returnLabel: "Простой возврат",
    genericPromotionTarget: "Специальные предложения",
    snippetHeader: "Brands",
    priceLanguageCode: "ru",
    promotionLanguageCode: "ru",
  },
  IL: {
    countryCode: "IL",
    countryNameZh: "以色列",
    languageCode: "iw",
    languageName: "Hebrew",
    style: "直接务实、强调品质与价值",
    currencyCode: "ILS",
    shippingLabel: "משלוח חינם",
    returnLabel: "החזרות קלות",
    genericPromotionTarget: "מבצעים מיוחדים",
    snippetHeader: "Brands",
    priceLanguageCode: "iw",
    promotionLanguageCode: "iw",
  },
  MX: {
    countryCode: "MX",
    countryNameZh: "墨西哥",
    languageCode: "es",
    languageName: "Spanish (MX)",
    style: "热情直接、强调优惠与便利",
    currencyCode: "MXN",
    shippingLabel: "Envío gratis",
    returnLabel: "Devoluciones fáciles",
    genericPromotionTarget: "Ofertas especiales",
    snippetHeader: "Brands",
    priceLanguageCode: "es",
    promotionLanguageCode: "es",
  },
  AR: {
    countryCode: "AR",
    countryNameZh: "阿根廷",
    languageCode: "es",
    languageName: "Spanish (AR)",
    style: "热情直接、强调优惠与购买动机",
    currencyCode: "ARS",
    shippingLabel: "Envío gratis",
    returnLabel: "Devoluciones fáciles",
    genericPromotionTarget: "Ofertas especiales",
    snippetHeader: "Brands",
    priceLanguageCode: "es",
    promotionLanguageCode: "es",
  },
  CL: {
    countryCode: "CL",
    countryNameZh: "智利",
    languageCode: "es",
    languageName: "Spanish (CL)",
    style: "友好直接、强调品质与优惠",
    currencyCode: "CLP",
    shippingLabel: "Envío gratis",
    returnLabel: "Devoluciones fáciles",
    genericPromotionTarget: "Ofertas especiales",
    snippetHeader: "Brands",
    priceLanguageCode: "es",
    promotionLanguageCode: "es",
  },
  CO: {
    countryCode: "CO",
    countryNameZh: "哥伦比亚",
    languageCode: "es",
    languageName: "Spanish (CO)",
    style: "友好热情、强调优惠与性价比",
    currencyCode: "COP",
    shippingLabel: "Envío gratis",
    returnLabel: "Devoluciones fáciles",
    genericPromotionTarget: "Ofertas especiales",
    snippetHeader: "Brands",
    priceLanguageCode: "es",
    promotionLanguageCode: "es",
  },
};

export function getAdMarketConfig(country?: string): AdMarketConfig {
  const key = String(country || "US").toUpperCase();
  return AD_MARKET_MAP[key] || DEFAULT_MARKET;
}

export function getLanguageCodeByCountry(country?: string): string {
  return getAdMarketConfig(country).languageCode;
}

const LANG_CODE_TO_NAME: Record<string, string> = {
  en: "English", fr: "French", de: "German", es: "Spanish",
  it: "Italian", pt: "Portuguese", nl: "Dutch", ja: "Japanese",
  ko: "Korean", zh_CN: "Simplified Chinese", zh_TW: "Traditional Chinese",
  ru: "Russian", pl: "Polish", sv: "Swedish", no: "Norwegian",
  da: "Danish", fi: "Finnish", cs: "Czech", tr: "Turkish",
  th: "Thai", vi: "Vietnamese", id: "Indonesian", ms: "Malay",
  ar: "Arabic", iw: "Hebrew", el: "Greek", ro: "Romanian",
  hu: "Hungarian", bg: "Bulgarian", hi: "Hindi",
};

export function getLanguageNameByCode(code?: string): string | undefined {
  if (!code) return undefined;
  return LANG_CODE_TO_NAME[code];
}

export function resolveLanguageName(country: string, adLanguageCode?: string): string {
  if (adLanguageCode) {
    const name = getLanguageNameByCode(adLanguageCode);
    if (name) return name;
  }
  return getAdMarketConfig(country).languageName;
}

export function getCurrencyCodeByCountry(country?: string): string {
  return getAdMarketConfig(country).currencyCode;
}

export function getPromotionLanguageCodeByCountry(country?: string): string {
  return getAdMarketConfig(country).promotionLanguageCode;
}

export function getPriceLanguageCodeByCountry(country?: string): string {
  return getAdMarketConfig(country).priceLanguageCode;
}

export function getSnippetHeaderByCountry(country?: string): string {
  return getAdMarketConfig(country).snippetHeader;
}
